server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/login
            filters:
              - name: OauthFilter
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/test
            filters:
              - name: OauthFilter2

